name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: node:22

    steps:
      - uses: actions/checkout@v4

      - run: npm i
      - run: npm run test
      
